// <auto-generated />
using Endeksa.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Endeksa.Repository.Migrations
{
    [DbContext(typeof(TkgmDbContext))]
    [Migration("20230121112827_FirstInitialize")]
    partial class FirstInitialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Endeksa.Core.Models.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeometryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GittigiParselListe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GittigiParselSebep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("MahalleAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MahalleId")
                        .HasColumnType("int");

                    b.Property<string>("Mevkii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nitelik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pafta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParselId")
                        .HasColumnType("int");

                    b.Property<string>("ParselNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZeminId")
                        .HasColumnType("int");

                    b.Property<string>("ZeminKmdurum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roots");
                });
#pragma warning restore 612, 618
        }
    }
}
