// <auto-generated />
using Endeksa.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Endeksa.Repository.Migrations
{
    [DbContext(typeof(TkgmDbContext))]
    [Migration("20230120103632_FirstInitialize")]
    partial class FirstInitialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Endeksa.Core.Models.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("adaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geometryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gittigiParselListe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gittigiParselSebep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilId")
                        .HasColumnType("int");

                    b.Property<string>("ilceAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.Property<string>("mahalleAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mahalleId")
                        .HasColumnType("int");

                    b.Property<string>("mevkii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nitelik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pafta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parselId")
                        .HasColumnType("int");

                    b.Property<string>("parselNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("zeminId")
                        .HasColumnType("int");

                    b.Property<string>("zeminKmdurum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roots");
                });
#pragma warning restore 612, 618
        }
    }
}
